/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fast_Food;

import com.sun.glass.events.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Component;
import static java.awt.PageAttributes.MediaType.C;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent; 


/**
 *
 * @author User1
 */
public class FastFood extends javax.swing.JFrame {

    /**
     * Creates new form FastFood
     */
    //declaring prices of the menu and initializing thier prices
    double Price_Bottle = 1.9;
    double Price_CheeseSand = 2.2;
    double Price_ChickenSalad = 2.2;
    double Price_ChickenSand = 2.2;
    double Price_ChocolateMilk = 1.2;
    double Price_Chocolate = 1.8;
    double Price_Coffee = 1.5;
    double Price_Cola = 0.89;
    double Price_FishSand = 2.7;
    double Price_Fries = 1.1;
    double Price_Hamburger = 2.27;
    double Price_Hash = 2.5;
    double Price_Onion = 0.56;
    double Price_Orange = 1.5;
    double Price_Pan  = 1.2;
    double Price_Pine = 1.7;
    double Price_Salad = 1.2;
    double Price_Strawberry = 1.4;
    double Price_Tea = 2.25;
    double Price_Toasted = 1.6;
    double Price_Vanilla = 1.5;
    
    //declaring and initializing the tax rate
    double Tax_Rate = 3.7;
    
    //declaring the following
    double iTax, iTotal,iSubTotal, iChange, iCost; 
    
    //declaring the array items amd initializing it
    double[] itemcost = new double[21];
    
    public FastFood() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtBtn14 = new javax.swing.JCheckBox();
        jtxtBtn15 = new javax.swing.JCheckBox();
        jtxtBtn16 = new javax.swing.JCheckBox();
        jtxtBtn17 = new javax.swing.JCheckBox();
        jtxtBtn18 = new javax.swing.JCheckBox();
        jtxtBtn19 = new javax.swing.JCheckBox();
        jtxtBtn20 = new javax.swing.JCheckBox();
        jtxtBtn21 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtTea = new javax.swing.JTextField();
        jtxtCola = new javax.swing.JTextField();
        jtxtCoffee = new javax.swing.JTextField();
        jtxtOrange = new javax.swing.JTextField();
        jtxtBottle = new javax.swing.JTextField();
        jtxtVanilla = new javax.swing.JTextField();
        jtxtStrawberry = new javax.swing.JTextField();
        jtxtChocolateMilk = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jtxtBtn9 = new javax.swing.JCheckBox();
        jtxtBtn10 = new javax.swing.JCheckBox();
        jtxtBtn11 = new javax.swing.JCheckBox();
        jtxtBtn12 = new javax.swing.JCheckBox();
        jtxtBtn13 = new javax.swing.JCheckBox();
        jtxtHash = new javax.swing.JTextField();
        jtxtToasted = new javax.swing.JTextField();
        jtxtPine = new javax.swing.JTextField();
        jtxtChocolate = new javax.swing.JTextField();
        jtxtPan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jtxtBtn1 = new javax.swing.JCheckBox();
        jtxtBtn2 = new javax.swing.JCheckBox();
        jtxtBtn3 = new javax.swing.JCheckBox();
        jtxtBtn4 = new javax.swing.JCheckBox();
        jtxtBtn5 = new javax.swing.JCheckBox();
        jtxtBtn7 = new javax.swing.JCheckBox();
        jtxtBtn8 = new javax.swing.JCheckBox();
        jtxtFries = new javax.swing.JTextField();
        jtxtSalad = new javax.swing.JTextField();
        jtxtHamburger = new javax.swing.JTextField();
        jtxtOnion = new javax.swing.JTextField();
        jtxtFishSand = new javax.swing.JTextField();
        jtxtCheeseSand = new javax.swing.JTextField();
        jtxtChickenSand = new javax.swing.JTextField();
        jtxtChickenSalad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtbtn6 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jcmbPaymentMehod = new javax.swing.JComboBox<>();
        jtxtPaymentMethod = new javax.swing.JTextField();
        jlblChange = new javax.swing.JTextField();
        jlblSubTotal = new javax.swing.JTextField();
        jlblTax = new javax.swing.JTextField();
        jlblTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtnTotal = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel1.setForeground(new java.awt.Color(51, 153, 0));
        jPanel1.setEnabled(false);

        jtxtBtn14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn14.setForeground(new java.awt.Color(51, 153, 0));
        jtxtBtn14.setText("Tea  $2.25");
        jtxtBtn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn14ActionPerformed(evt);
            }
        });

        jtxtBtn15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn15.setForeground(new java.awt.Color(51, 153, 0));
        jtxtBtn15.setText("Cola  $0.89");
        jtxtBtn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn15ActionPerformed(evt);
            }
        });

        jtxtBtn16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn16.setForeground(new java.awt.Color(51, 153, 0));
        jtxtBtn16.setText("Cofffee  $1.5");
        jtxtBtn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn16ActionPerformed(evt);
            }
        });

        jtxtBtn17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn17.setForeground(new java.awt.Color(51, 153, 0));
        jtxtBtn17.setText("Orange  $1.5");
        jtxtBtn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn17ActionPerformed(evt);
            }
        });

        jtxtBtn18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn18.setForeground(new java.awt.Color(51, 153, 0));
        jtxtBtn18.setText("Bottle Water   $1.9");
        jtxtBtn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn18ActionPerformed(evt);
            }
        });

        jtxtBtn19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn19.setForeground(new java.awt.Color(51, 153, 0));
        jtxtBtn19.setText("Vanilla Cone  $1.6");
        jtxtBtn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn19ActionPerformed(evt);
            }
        });

        jtxtBtn20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn20.setForeground(new java.awt.Color(51, 153, 0));
        jtxtBtn20.setText("Strawberry Shake  $1.4");
        jtxtBtn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn20ActionPerformed(evt);
            }
        });

        jtxtBtn21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn21.setForeground(new java.awt.Color(51, 153, 0));
        jtxtBtn21.setText("Chocolate Milk Shake  $1.2");
        jtxtBtn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn21ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("Drinks");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 0));
        jLabel7.setText("Shakes");

        jtxtTea.setForeground(new java.awt.Color(51, 153, 0));
        jtxtTea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTea.setText("0");
        jtxtTea.setEnabled(false);
        jtxtTea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTeaKeyTyped(evt);
            }
        });

        jtxtCola.setForeground(new java.awt.Color(51, 153, 0));
        jtxtCola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCola.setText("0");
        jtxtCola.setEnabled(false);
        jtxtCola.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtColaKeyTyped(evt);
            }
        });

        jtxtCoffee.setForeground(new java.awt.Color(51, 153, 0));
        jtxtCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCoffee.setText("0");
        jtxtCoffee.setEnabled(false);
        jtxtCoffee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCoffeeKeyTyped(evt);
            }
        });

        jtxtOrange.setForeground(new java.awt.Color(51, 153, 0));
        jtxtOrange.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtOrange.setText("0");
        jtxtOrange.setEnabled(false);
        jtxtOrange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtOrangeKeyTyped(evt);
            }
        });

        jtxtBottle.setForeground(new java.awt.Color(51, 153, 0));
        jtxtBottle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBottle.setText("0");
        jtxtBottle.setEnabled(false);
        jtxtBottle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBottleKeyTyped(evt);
            }
        });

        jtxtVanilla.setForeground(new java.awt.Color(51, 153, 0));
        jtxtVanilla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVanilla.setText("0");
        jtxtVanilla.setEnabled(false);
        jtxtVanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtVanillaActionPerformed(evt);
            }
        });
        jtxtVanilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtVanillaKeyTyped(evt);
            }
        });

        jtxtStrawberry.setForeground(new java.awt.Color(51, 153, 0));
        jtxtStrawberry.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtStrawberry.setText("0");
        jtxtStrawberry.setEnabled(false);
        jtxtStrawberry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtStrawberryKeyTyped(evt);
            }
        });

        jtxtChocolateMilk.setForeground(new java.awt.Color(51, 153, 0));
        jtxtChocolateMilk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChocolateMilk.setText("0");
        jtxtChocolateMilk.setEnabled(false);
        jtxtChocolateMilk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtChocolateMilkKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtBtn14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtBtn15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtBtn16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtBtn17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtBtn18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtBtn19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtBtn20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtBtn21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtTea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(jtxtCola, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtCoffee, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtOrange, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtBottle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtVanilla, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtStrawberry, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtChocolateMilk, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn14)
                    .addComponent(jtxtTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn15)
                    .addComponent(jtxtCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn16)
                    .addComponent(jtxtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn17)
                    .addComponent(jtxtOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn18)
                    .addComponent(jtxtBottle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn19)
                    .addComponent(jtxtVanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn20)
                    .addComponent(jtxtStrawberry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn21)
                    .addComponent(jtxtChocolateMilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 360, 520));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));

        jtxtBtn9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn9.setForeground(new java.awt.Color(153, 0, 153));
        jtxtBtn9.setText("Hash Brown  $2.5");
        jtxtBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn9ActionPerformed(evt);
            }
        });

        jtxtBtn10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn10.setForeground(new java.awt.Color(153, 0, 153));
        jtxtBtn10.setText("Toasted Bagel  $1.6");
        jtxtBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn10ActionPerformed(evt);
            }
        });

        jtxtBtn11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn11.setForeground(new java.awt.Color(153, 0, 153));
        jtxtBtn11.setText("Pineapple Stick  $1.7");
        jtxtBtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn11ActionPerformed(evt);
            }
        });

        jtxtBtn12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn12.setForeground(new java.awt.Color(153, 0, 153));
        jtxtBtn12.setText("Chocolate Muffin  $1.8");
        jtxtBtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn12ActionPerformed(evt);
            }
        });

        jtxtBtn13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn13.setForeground(new java.awt.Color(153, 0, 153));
        jtxtBtn13.setText("Pancake Syrup  $1.2");
        jtxtBtn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn13ActionPerformed(evt);
            }
        });

        jtxtHash.setForeground(new java.awt.Color(51, 153, 0));
        jtxtHash.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtHash.setText("0");
        jtxtHash.setEnabled(false);
        jtxtHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtHashActionPerformed(evt);
            }
        });
        jtxtHash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtHashKeyTyped(evt);
            }
        });

        jtxtToasted.setForeground(new java.awt.Color(51, 153, 0));
        jtxtToasted.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtToasted.setText("0");
        jtxtToasted.setEnabled(false);
        jtxtToasted.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtToastedKeyTyped(evt);
            }
        });

        jtxtPine.setForeground(new java.awt.Color(51, 153, 0));
        jtxtPine.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPine.setText("0");
        jtxtPine.setEnabled(false);
        jtxtPine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPineKeyTyped(evt);
            }
        });

        jtxtChocolate.setForeground(new java.awt.Color(51, 153, 0));
        jtxtChocolate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChocolate.setText("0");
        jtxtChocolate.setEnabled(false);
        jtxtChocolate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtChocolateKeyTyped(evt);
            }
        });

        jtxtPan.setForeground(new java.awt.Color(51, 153, 0));
        jtxtPan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPan.setText("0");
        jtxtPan.setEnabled(false);
        jtxtPan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPanKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 153));
        jLabel5.setText("Dessert");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtBtn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtBtn10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtBtn11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtBtn12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtBtn13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jtxtHash, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtToasted, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPine, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPan, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn9)
                    .addComponent(jtxtHash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn10)
                    .addComponent(jtxtToasted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn11)
                    .addComponent(jtxtPine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn12)
                    .addComponent(jtxtChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn13)
                    .addComponent(jtxtPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 410, 270));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel3.setEnabled(false);

        jtxtBtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn1.setForeground(new java.awt.Color(0, 153, 153));
        jtxtBtn1.setText("Fries  $1.1");
        jtxtBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn1ActionPerformed(evt);
            }
        });

        jtxtBtn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn2.setForeground(new java.awt.Color(0, 153, 153));
        jtxtBtn2.setText("Salad  $1.2");
        jtxtBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn2ActionPerformed(evt);
            }
        });

        jtxtBtn3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn3.setForeground(new java.awt.Color(0, 153, 153));
        jtxtBtn3.setText("Hamburger  $2.27");
        jtxtBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn3ActionPerformed(evt);
            }
        });

        jtxtBtn4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn4.setForeground(new java.awt.Color(0, 153, 153));
        jtxtBtn4.setText("Onion Rings  $0.56");
        jtxtBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn4ActionPerformed(evt);
            }
        });

        jtxtBtn5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn5.setForeground(new java.awt.Color(0, 153, 153));
        jtxtBtn5.setText("Chicken Salad  $2.2");
        jtxtBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn5ActionPerformed(evt);
            }
        });

        jtxtBtn7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn7.setForeground(new java.awt.Color(0, 153, 153));
        jtxtBtn7.setText("Cheese Sandwich  $2.2");
        jtxtBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn7ActionPerformed(evt);
            }
        });

        jtxtBtn8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBtn8.setForeground(new java.awt.Color(0, 153, 153));
        jtxtBtn8.setText("Chicken Sandwich  $2.2");
        jtxtBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBtn8ActionPerformed(evt);
            }
        });

        jtxtFries.setForeground(new java.awt.Color(51, 153, 0));
        jtxtFries.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFries.setText("0");
        jtxtFries.setEnabled(false);
        jtxtFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFriesActionPerformed(evt);
            }
        });
        jtxtFries.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtFriesKeyTyped(evt);
            }
        });

        jtxtSalad.setForeground(new java.awt.Color(51, 153, 0));
        jtxtSalad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtSalad.setText("0");
        jtxtSalad.setEnabled(false);
        jtxtSalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSaladActionPerformed(evt);
            }
        });
        jtxtSalad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtSaladKeyTyped(evt);
            }
        });

        jtxtHamburger.setForeground(new java.awt.Color(51, 153, 0));
        jtxtHamburger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtHamburger.setText("0");
        jtxtHamburger.setEnabled(false);
        jtxtHamburger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtHamburgerKeyTyped(evt);
            }
        });

        jtxtOnion.setForeground(new java.awt.Color(51, 153, 0));
        jtxtOnion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtOnion.setText("0");
        jtxtOnion.setEnabled(false);
        jtxtOnion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtOnionKeyTyped(evt);
            }
        });

        jtxtFishSand.setForeground(new java.awt.Color(51, 153, 0));
        jtxtFishSand.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFishSand.setText("0");
        jtxtFishSand.setEnabled(false);
        jtxtFishSand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtFishSandKeyTyped(evt);
            }
        });

        jtxtCheeseSand.setForeground(new java.awt.Color(51, 153, 0));
        jtxtCheeseSand.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCheeseSand.setText("0");
        jtxtCheeseSand.setEnabled(false);
        jtxtCheeseSand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCheeseSandKeyTyped(evt);
            }
        });

        jtxtChickenSand.setForeground(new java.awt.Color(51, 153, 0));
        jtxtChickenSand.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenSand.setText("0");
        jtxtChickenSand.setEnabled(false);
        jtxtChickenSand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtChickenSandKeyTyped(evt);
            }
        });

        jtxtChickenSalad.setForeground(new java.awt.Color(51, 153, 0));
        jtxtChickenSalad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenSalad.setText("0");
        jtxtChickenSalad.setEnabled(false);
        jtxtChickenSalad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtChickenSaladKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Fast Meal and Vegetarian");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Sandwich");

        jtxtbtn6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtbtn6.setForeground(new java.awt.Color(0, 153, 153));
        jtxtbtn6.setText("Fish Sandwich  $2.7");
        jtxtbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtbtn6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtBtn1)
                            .addComponent(jtxtBtn2)
                            .addComponent(jtxtBtn3)
                            .addComponent(jtxtBtn4)
                            .addComponent(jtxtBtn5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtChickenSalad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtOnion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtHamburger, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtSalad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtFries, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtxtBtn7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtBtn8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jtxtbtn6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtFishSand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCheeseSand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtChickenSand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn1)
                    .addComponent(jtxtFries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn2)
                    .addComponent(jtxtSalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn3)
                    .addComponent(jtxtHamburger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn4)
                    .addComponent(jtxtOnion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn5)
                    .addComponent(jtxtChickenSalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFishSand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtbtn6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn7)
                    .addComponent(jtxtCheeseSand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBtn8)
                    .addComponent(jtxtChickenSand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 320, 520));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel4.setForeground(java.awt.Color.cyan);
        jPanel4.setToolTipText("Fast Food Restaurant");
        jPanel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 102));
        jLabel11.setText("Fast Food Restaurant");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 1110, 110));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));

        jcmbPaymentMehod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcmbPaymentMehod.setForeground(new java.awt.Color(0, 0, 255));
        jcmbPaymentMehod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debit Card", "Master Card", "Visa Card" }));
        jcmbPaymentMehod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbPaymentMehodActionPerformed(evt);
            }
        });

        jtxtPaymentMethod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPaymentMethod.setText("0");
        jtxtPaymentMethod.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 51)));
        jtxtPaymentMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPaymentMethodActionPerformed(evt);
            }
        });

        jlblTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblTaxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Change");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Tax");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Sub Total");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Total");

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnTotal.setForeground(new java.awt.Color(0, 51, 153));
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jbtnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnClear.setForeground(new java.awt.Color(0, 51, 153));
        jbtnClear.setText("Clear");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(0, 51, 153));
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setText("Payment Method");

        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 51)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jbtnTotal)
                                .addGap(89, 89, 89))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(19, 19, 19))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(jcmbPaymentMehod, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(jtxtPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))))
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblSubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblChange, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtnClear)
                        .addGap(74, 74, 74)
                        .addComponent(jbtnExit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jcmbPaymentMehod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jtxtPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jlblChange, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlblSubTotal)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnExit)
                    .addComponent(jbtnClear)
                    .addComponent(jbtnTotal))
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 410, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private JFrame frame; //declaring frame
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit"); // create the frame 
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Fast Food", //creates a content pane (which is a confirm dialog) 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION);{ // gives a user an option of a yes or no.
          System.exit(0); //Exits the system.
    }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        // This line of code set the text thatyou have entered to null thus cleas the text.
        jtxtFries.setText("0");
        jtxtSalad.setText("0");
        jtxtHamburger.setText("0");
        jtxtOnion.setText("0");
        jtxtChickenSalad.setText("0");
        jtxtCheeseSand.setText("0");
        jtxtFishSand.setText("0");
        jtxtChickenSand.setText("0");
        jtxtHash.setText("0");
        jtxtToasted.setText("0");
        jtxtChocolate.setText("0");
        jtxtPine.setText("0");
        jtxtPan.setText("0");
        jtxtTea.setText("0");
        jtxtCola.setText("0");
        jtxtCoffee.setText("0");
        jtxtOrange.setText("0");
        jtxtBottle.setText("0");
        jtxtVanilla.setText("0");
        jtxtStrawberry.setText("0");
        jtxtChocolateMilk.setText("0");
        jtxtPaymentMethod.setText("0");
        
        jtxtFries.setEnabled(false);
        jtxtChocolateMilk.setEnabled(false);
        jtxtStrawberry.setEnabled(false);
        jtxtVanilla.setEnabled(false);
        jtxtBottle.setEnabled(false);
        jtxtOrange.setEnabled(false);      
        jtxtCoffee.setEnabled(false);       
        jtxtCola.setEnabled(false);        
        jtxtTea.setEnabled(false);        
        jtxtPan.setEnabled(false);       
        jtxtPine.setEnabled(false);     
        jtxtChocolate.setEnabled(false);
        jtxtToasted.setEnabled(false);        
        jtxtHash.setEnabled(false);        
        jtxtChickenSand.setEnabled(false);        
        jtxtChickenSalad.setEnabled(false);        
        jtxtOnion.setEnabled(false);       
        jtxtHamburger.setEnabled(false);        
        jtxtSalad.setEnabled(false);
                
        //This line of code selected button to null thus it unchecks the checked button.
        jtxtBtn1.setSelected(false);
        jtxtBtn2.setSelected(false);
        jtxtBtn3.setSelected(false);
        jtxtBtn4.setSelected(false);
        jtxtBtn5.setSelected(false);
        jtxtbtn6.setSelected(false);
        jtxtBtn7.setSelected(false);
        jtxtBtn8.setSelected(false);
        jtxtBtn9.setSelected(false);
        jtxtBtn10.setSelected(false);
        jtxtBtn11.setSelected(false);
        jtxtBtn12.setSelected(false);
        jtxtBtn13.setSelected(false);
        jtxtBtn14.setSelected(false);
        jtxtBtn15.setSelected(false);
        jtxtBtn16.setSelected(false);
        jtxtBtn17.setSelected(false);
        jtxtBtn18.setSelected(false);
        jtxtBtn19.setSelected(false);
        jtxtBtn21.setSelected(false);
        jtxtBtn20.setSelected(false);
        
        jlblTax.setText(null);
        jlblTotal.setText(null);
        jlblSubTotal.setText(null);
        jlblChange.setText(null);
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jtxtVanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtVanillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtVanillaActionPerformed

    private void jtxtFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFriesActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jtxtFriesActionPerformed

    private void jtxtFriesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtFriesKeyTyped
        // TODO add your handling code here:
         char NumberOnly = evt.getKeyChar(); //declearing a character numberonly and assigns it to a readable key character.
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
            evt.consume();
        }         
    }//GEN-LAST:event_jtxtFriesKeyTyped

    private void jtxtSaladKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSaladKeyTyped
        // TODO add your handling code here:
       char NumberOnly = evt.getKeyChar();
       if(!(Character.isDigit(NumberOnly))
       ||(NumberOnly == KeyEvent.VK_BACKSPACE)
       ||(NumberOnly == KeyEvent.VK_DELETE)){
           evt.consume();
       }
    }//GEN-LAST:event_jtxtSaladKeyTyped

    private void jtxtHamburgerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtHamburgerKeyTyped
        // TODO add your handling code here:
        char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
            evt.consume();
    }//GEN-LAST:event_jtxtHamburgerKeyTyped
  }
    private void jtxtOnionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtOnionKeyTyped
        // TODO add your handling code here:
        char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtOnionKeyTyped

    private void jtxtChickenSaladKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChickenSaladKeyTyped
        // TODO add your handling code here:
         char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtChickenSaladKeyTyped

    private void jtxtFishSandKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtFishSandKeyTyped
        // TODO add your handling code here:
         char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtFishSandKeyTyped

    private void jtxtCheeseSandKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCheeseSandKeyTyped
        // TODO add your handling code here:
         char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtCheeseSandKeyTyped

    private void jtxtChickenSandKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChickenSandKeyTyped
        // TODO add your handling code here:
         char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtChickenSandKeyTyped

    private void jtxtHashKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtHashKeyTyped
        // TODO add your handling code here:
         char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtHashKeyTyped

    private void jtxtToastedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtToastedKeyTyped
        // TODO add your handling code here:
         char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtToastedKeyTyped

    private void jtxtPineKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPineKeyTyped
        // TODO add your handling code here:
         char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtPineKeyTyped

    private void jtxtChocolateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChocolateKeyTyped
        // TODO add your handling code here:
         char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtChocolateKeyTyped

    private void jtxtPanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPanKeyTyped
        // TODO add your handling code here:
         char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtPanKeyTyped

    private void jtxtTeaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTeaKeyTyped
        // TODO add your handling code here:
         char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtTeaKeyTyped

    private void jtxtColaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtColaKeyTyped
        // TODO add your handling code here:
         char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtColaKeyTyped

    private void jtxtCoffeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCoffeeKeyTyped
        // TODO add your handling code here:
         char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtCoffeeKeyTyped

    private void jtxtOrangeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtOrangeKeyTyped
        // TODO add your handling code here:
         char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtOrangeKeyTyped

    private void jtxtBottleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBottleKeyTyped
        // TODO add your handling code here:
         char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtBottleKeyTyped

    private void jtxtVanillaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtVanillaKeyTyped
        // TODO add your handling code here:
        char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtVanillaKeyTyped

    private void jtxtStrawberryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtStrawberryKeyTyped
        // TODO add your handling code here:
        char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtStrawberryKeyTyped

    private void jtxtChocolateMilkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChocolateMilkKeyTyped
        // TODO add your handling code here:
        char NumberOnly = evt.getKeyChar();
        if(!(Character.isDigit(NumberOnly))
        || (NumberOnly == KeyEvent.VK_BACKSPACE)
        || (NumberOnly == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtChocolateMilkKeyTyped

    private void jtxtBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn1ActionPerformed
        // TODO add your handling code here:
        if(jtxtBtn1.isSelected()){
            jtxtFries.setEnabled(true);
            jtxtFries.requestFocus();
            jtxtFries.setText("");
        }else{
            jtxtFries.setEnabled(false);
            jtxtFries.setText("0");
        }
    }//GEN-LAST:event_jtxtBtn1ActionPerformed

    private void jtxtBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn2ActionPerformed
        // TODO add your handling code here:
        if(jtxtBtn2.isSelected()){
            jtxtSalad.setEnabled(true);
            jtxtSalad.requestFocus();
            jtxtSalad.setText("");
        }else{
            jtxtSalad.setEnabled(true);
            jtxtSalad.setText("0");
        }
        
    }//GEN-LAST:event_jtxtBtn2ActionPerformed

    private void jtxtBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn3ActionPerformed
        // TODO add your handling code here:
        if(jtxtBtn3.isSelected()){
            jtxtHamburger.setEnabled(true);
            jtxtHamburger.requestFocus();
            jtxtHamburger.setText("");
        }else{
            jtxtHamburger.setEnabled(false);
            jtxtHamburger.setText("0");
        }
    }//GEN-LAST:event_jtxtBtn3ActionPerformed

    private void jtxtBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn4ActionPerformed
        // TODO add your handling code here:
        if(jtxtBtn4.isSelected()){
            jtxtOnion.setEnabled(true);
            jtxtOnion.requestFocus();
            jtxtOnion.setText("");
        }else{
            jtxtOnion.setEnabled(false);
            jtxtOnion.setText("0");
        }
    }//GEN-LAST:event_jtxtBtn4ActionPerformed

    private void jtxtBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn5ActionPerformed
        // TODO add your handling code here:
        if(jtxtBtn4.isSelected()){
            jtxtChickenSalad.setEnabled(true);
            jtxtChickenSalad.requestFocus();
            jtxtChickenSalad.setText("");
        }else{
            jtxtChickenSalad.setEnabled(false);
            jtxtChickenSalad.setText("0");
        }
    }//GEN-LAST:event_jtxtBtn5ActionPerformed

    private void jtxtBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn8ActionPerformed
        // TODO add your handling code here:
        if(jtxtBtn8.isSelected()){
            jtxtChickenSand.setEnabled(true);
            jtxtChickenSand.requestFocus();
            jtxtChickenSand.setText("");
        }else{
            jtxtChickenSand.setEnabled(false);
            jtxtChickenSand.setText("0");
        }  
    }//GEN-LAST:event_jtxtBtn8ActionPerformed

    private void jtxtbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtbtn6ActionPerformed
        // TODO add your handling code here:
        if(jtxtbtn6.isSelected()){
            jtxtFishSand.setEnabled(true);
            jtxtFishSand.requestFocus();
            jtxtFishSand.setText("");
        }else{
            jtxtFishSand.setEnabled(false);
            jtxtFishSand.setText("0");
        }
    }//GEN-LAST:event_jtxtbtn6ActionPerformed

    private void jtxtBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn7ActionPerformed
        // TODO add your handling code here:
        if(jtxtBtn7.isSelected()){
            jtxtCheeseSand.setEnabled(true);
            jtxtCheeseSand.requestFocus();
            jtxtCheeseSand.setText("");
        }else{
            jtxtCheeseSand.setEnabled(false);
            jtxtCheeseSand.setText("0");
        }
    }//GEN-LAST:event_jtxtBtn7ActionPerformed

    private void jtxtBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn9ActionPerformed
        // TODO add your handling code here:
        if(jtxtBtn9.isSelected()){
            jtxtHash.setEnabled(true);
            jtxtHash.requestFocus();
            jtxtHash.setText("");
            
        }else{
            jtxtHash.setEnabled(false);
            jtxtHash.setText("0");
        }
    }//GEN-LAST:event_jtxtBtn9ActionPerformed

    private void jtxtBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn10ActionPerformed
        // TODO add your handling code here:
        if(jtxtBtn10.isSelected()){
            jtxtToasted.setEnabled(true);
            jtxtToasted.requestFocus();
            jtxtToasted.setText("");
            
        }else{
            jtxtToasted.setEnabled(false);
            jtxtToasted.setText("0");
        }
    }//GEN-LAST:event_jtxtBtn10ActionPerformed

    private void jtxtBtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn11ActionPerformed
        // TODO add your handling code here:
        if(jtxtBtn11.isSelected()){
            jtxtPine.setEnabled(true);
            jtxtPine.requestFocus();
            jtxtPine.setText("");
        }else{
            jtxtPine.setEnabled(false);
            jtxtPine.setText("0");
        }
    }//GEN-LAST:event_jtxtBtn11ActionPerformed

    private void jtxtBtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn12ActionPerformed
        // TODO add your handling code here:
        if(jtxtBtn12.isSelected()){
            jtxtChocolate.setEnabled(true);
            jtxtChocolate.requestFocus();
            jtxtChocolate.setText("");
        }else{
            jtxtChocolate.setEnabled(false);
            jtxtChocolate.setText("0");
        }
    }//GEN-LAST:event_jtxtBtn12ActionPerformed

    private void jtxtBtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn13ActionPerformed
        // TODO add your handling code here:
        if(jtxtBtn13.isSelected()){
            jtxtPan.setEnabled(true);
            jtxtPan.requestFocus();
            jtxtPan.setText("");
        }else{
            jtxtPan.setEnabled(false);
            jtxtPan.setText("0");
        }
    }//GEN-LAST:event_jtxtBtn13ActionPerformed

    private void jtxtBtn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn14ActionPerformed
        // TODO add your handling code here:
        if(jtxtBtn14.isSelected()){
            jtxtTea.setEnabled(true);
            jtxtTea.requestFocus();
            jtxtTea.setText("");
        }else{
            jtxtTea.setEnabled(false);
            jtxtTea.setText("0");
        }
    }//GEN-LAST:event_jtxtBtn14ActionPerformed

    private void jtxtBtn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn15ActionPerformed
        // TODO add your handling code here:
        if(jtxtBtn15.isSelected()){
            jtxtCola.setEnabled(true);
            jtxtCola.requestFocus();
            jtxtCola.setText("");
        }else{
            jtxtCola.setEnabled(false);
            jtxtCola.setText("0");
        }
    }//GEN-LAST:event_jtxtBtn15ActionPerformed

    private void jtxtBtn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn16ActionPerformed
        // TODO add your handling code here:
          if(jtxtBtn16.isSelected()){ 
              jtxtCoffee.setEnabled(true);
              jtxtCoffee.requestFocus();
              jtxtCoffee.setText("");
            }else{
              jtxtCoffee.setEnabled(false);
              jtxtCoffee.setText("0");
          }
    }//GEN-LAST:event_jtxtBtn16ActionPerformed

    private void jtxtBtn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn17ActionPerformed
        // TODO add your handling code here:
         if(jtxtBtn17.isSelected()){
             jtxtOrange.setEnabled(true);
             jtxtOrange.requestFocus();
             jtxtOrange.setText("");
         }else{
             jtxtOrange.setEnabled(false);
             jtxtOrange.setText("0");
         }          
    
    }//GEN-LAST:event_jtxtBtn17ActionPerformed

    private void jtxtBtn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn18ActionPerformed
        // TODO add your handling code here:
             if(jtxtBtn18.isSelected()){
                 jtxtBottle.setEnabled(true);
                 jtxtBottle.requestFocus();
                 jtxtBottle.setText("");
             }else{
                 jtxtBottle.setEnabled(false);
                 jtxtBottle.setText("0");
             }
    }//GEN-LAST:event_jtxtBtn18ActionPerformed

    private void jtxtBtn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn19ActionPerformed
        // TODO add your handling code here:
             if(jtxtBtn19.isSelected()){       
                 jtxtVanilla.setEnabled(true);
                 jtxtVanilla.requestFocus();
                 jtxtVanilla.setText("");
              }else{
                 jtxtVanilla.setEnabled(false);
                 jtxtVanilla.setText("0");
             }
    }//GEN-LAST:event_jtxtBtn19ActionPerformed

    private void jtxtBtn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn20ActionPerformed
        // TODO add your handling code here:
            if(jtxtBtn20.isSelected()){
                jtxtStrawberry.setEnabled(true);
                jtxtStrawberry.requestFocus();
                jtxtStrawberry.setText("");
              }else{
                jtxtStrawberry.setEditable(false);
                jtxtStrawberry.setText("0");
            }
    }//GEN-LAST:event_jtxtBtn20ActionPerformed

    private void jtxtBtn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBtn21ActionPerformed
        // TODO add your handling code here:
             if(jtxtBtn21.isSelected()){
                    jtxtChocolateMilk.setEnabled(true);
                    jtxtChocolateMilk.requestFocus();
                    jtxtChocolateMilk.setText("");
                }else{
                 jtxtChocolateMilk.setEnabled(false);
                 jtxtChocolateMilk.setText("0");
             }
    }//GEN-LAST:event_jtxtBtn21ActionPerformed

    private void jtxtHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtHashActionPerformed

    private void jtxtSaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSaladActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSaladActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        // TODO add your handling code here:
        
        //accessing each array and storing the value of jtxt________. and changing  them to double values
        itemcost[0] =Double.parseDouble(jtxtTea.getText());
        itemcost[1] =Double.parseDouble(jtxtFries.getText());
        itemcost[2] =Double.parseDouble(jtxtCoffee.getText());
        itemcost[3] =Double.parseDouble(jtxtCola.getText());
        itemcost[4] =Double.parseDouble(jtxtOnion.getText());
        itemcost[5] =Double.parseDouble(jtxtChocolate.getText());
        itemcost[6] =Double.parseDouble(jtxtChickenSand.getText());
        itemcost[7] =Double.parseDouble(jtxtChickenSalad.getText());
        itemcost[8] =Double.parseDouble(jtxtCheeseSand.getText());
        itemcost[9] =Double.parseDouble(jtxtHash.getText());
        itemcost[10] =Double.parseDouble(jtxtBottle.getText());
        itemcost[11] =Double.parseDouble(jtxtStrawberry.getText());
        itemcost[12] =Double.parseDouble(jtxtChocolateMilk.getText());
        itemcost[13] =Double.parseDouble(jtxtPan.getText());
        itemcost[14] =Double.parseDouble(jtxtPine.getText());
        itemcost[15] =Double.parseDouble(jtxtVanilla.getText());
        itemcost[16] =Double.parseDouble(jtxtOrange.getText());
        itemcost[17] =Double.parseDouble(jtxtToasted.getText());
        itemcost[18] =Double.parseDouble(jtxtSalad.getText());
        itemcost[19] =Double.parseDouble(jtxtFishSand.getText());
        itemcost[20] =Double.parseDouble(jtxtHamburger.getText());
        
        iChange = Double.parseDouble(jtxtPaymentMethod.getText());
        
        String PaymentMethod = (String) jcmbPaymentMehod.getSelectedItem();// getSelectedItem
        
        if(PaymentMethod == "cash"){
            
        iSubTotal = itemcost[0] + itemcost[1] + itemcost[2] + itemcost[3] + itemcost[4] +itemcost[5] +
                    itemcost[6] + itemcost[7] + itemcost[8] + itemcost[9] + itemcost[10] + itemcost[11] +
                    itemcost[12] + itemcost[13] + itemcost[14] + itemcost[15] + itemcost[16] + itemcost[17] +
                    itemcost[18] + itemcost[19] + itemcost[20] ;
        
        if(iChange >= iSubTotal)
        {    
        iTax = (iSubTotal * Tax_Rate)/100;
        
        String cTax = String.format("$%.2f", iTax); 
        jlblTax.setText(cTax);
        
        String cSubTotal = String.format("$%.2f",iSubTotal);
        jlblSubTotal.setText(cSubTotal);
        
        String cTotal = String.format("$%.2f",iSubTotal + iTax);
        jlblTotal.setText(cTotal);
        
        String cChange = String.format("$%.2f",iChange - (iSubTotal + iTax));
        jlblChange.setText(cChange);
          }
        else{
            JOptionPane.showMessageDialog(null, "Not enough cash", "Fast Food", JOptionPane.OK_OPTION);
        }
        }
        else if(PaymentMethod == "Debit Card" || PaymentMethod == "Master Card" || PaymentMethod == "Visa Card"){
                  
        iSubTotal = itemcost[0] + itemcost[1] + itemcost[2] + itemcost[3] + itemcost[4] +itemcost[5] +
                    itemcost[6] + itemcost[7] + itemcost[8] + itemcost[9] + itemcost[10] + itemcost[11] +
                    itemcost[12] + itemcost[13] + itemcost[14] + itemcost[15] + itemcost[16] + itemcost[17] +
                    itemcost[18] + itemcost[19] + itemcost[20] ;
        
        iTax = (iSubTotal * Tax_Rate)/100;
        
        String cTax = String.format("$%.2f", iTax); 
        jlblTax.setText(cTax);
        
        String cSubTotal = String.format("$%.2f",iSubTotal);
        jlblSubTotal.setText(cSubTotal);
        
        String cTotal = String.format("$%.2f",iSubTotal + iTax);
        jlblTotal.setText(cTotal);
        }
        
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jlblTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblTaxActionPerformed

    private void jtxtPaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPaymentMethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPaymentMethodActionPerformed

    private void jcmbPaymentMehodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbPaymentMehodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbPaymentMehodActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JComboBox<String> jcmbPaymentMehod;
    private javax.swing.JTextField jlblChange;
    private javax.swing.JTextField jlblSubTotal;
    private javax.swing.JTextField jlblTax;
    private javax.swing.JTextField jlblTotal;
    private javax.swing.JTextField jtxtBottle;
    private javax.swing.JCheckBox jtxtBtn1;
    private javax.swing.JCheckBox jtxtBtn10;
    private javax.swing.JCheckBox jtxtBtn11;
    private javax.swing.JCheckBox jtxtBtn12;
    private javax.swing.JCheckBox jtxtBtn13;
    private javax.swing.JCheckBox jtxtBtn14;
    private javax.swing.JCheckBox jtxtBtn15;
    private javax.swing.JCheckBox jtxtBtn16;
    private javax.swing.JCheckBox jtxtBtn17;
    private javax.swing.JCheckBox jtxtBtn18;
    private javax.swing.JCheckBox jtxtBtn19;
    private javax.swing.JCheckBox jtxtBtn2;
    private javax.swing.JCheckBox jtxtBtn20;
    private javax.swing.JCheckBox jtxtBtn21;
    private javax.swing.JCheckBox jtxtBtn3;
    private javax.swing.JCheckBox jtxtBtn4;
    private javax.swing.JCheckBox jtxtBtn5;
    private javax.swing.JCheckBox jtxtBtn7;
    private javax.swing.JCheckBox jtxtBtn8;
    private javax.swing.JCheckBox jtxtBtn9;
    private javax.swing.JTextField jtxtCheeseSand;
    private javax.swing.JTextField jtxtChickenSalad;
    private javax.swing.JTextField jtxtChickenSand;
    private javax.swing.JTextField jtxtChocolate;
    private javax.swing.JTextField jtxtChocolateMilk;
    private javax.swing.JTextField jtxtCoffee;
    private javax.swing.JTextField jtxtCola;
    private javax.swing.JTextField jtxtFishSand;
    private javax.swing.JTextField jtxtFries;
    private javax.swing.JTextField jtxtHamburger;
    private javax.swing.JTextField jtxtHash;
    private javax.swing.JTextField jtxtOnion;
    private javax.swing.JTextField jtxtOrange;
    private javax.swing.JTextField jtxtPan;
    private javax.swing.JTextField jtxtPaymentMethod;
    private javax.swing.JTextField jtxtPine;
    private javax.swing.JTextField jtxtSalad;
    private javax.swing.JTextField jtxtStrawberry;
    private javax.swing.JTextField jtxtTea;
    private javax.swing.JTextField jtxtToasted;
    private javax.swing.JTextField jtxtVanilla;
    private javax.swing.JCheckBox jtxtbtn6;
    // End of variables declaration//GEN-END:variables
}
